#ifndef APPLICATION_H_INCLUDED
#define APPLICATION_H_INCLUDED

#include "../Admin/admin.h"
#include "../Clinic/clinic.h"


typedef enum EN_mode_t
{
	ADMIN, USER
} EN_mode_t;


typedef enum EN_operation_t
{
	ADMIN_OPERATION_REGISTER_NEW_PATIENT, ADMIN_OPERATION_EDIT_PATIENT, ADMIN_OPERATION_RESERVE,
	ADMIN_OPERATION_CANCEL_RESERVATION, ADMIN_OPERATION_EDIT_RESERVATION, LOGOUT,
	USER_OPERATION_VIEW_PATIENT_RECORD = 0, USER_OPERATION_TODAY_RESERVATION = 1, EXIT_FROM_USER_MODE
} EN_operation_t;



void setup();
void appStart();


#endif // APPLICATION_H_INCLUDED